<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="rspec" tests="3" skipped="0" failures="0" errors="0" time="494.148250" timestamp="2023-08-02T05:15:08+00:00" hostname="runner">
<properties>
<property name="seed" value="38266"/>
</properties>
<testcase classname="spec.features.foo_spec" name="foo" file="./spec/features/foo_spec.rb" time="37.832874"></testcase>
<testcase classname="spec.features.bar_spec" name="bar" file="./spec/features/bar_spec.rb" time="32.502537"></testcase>

<testcase classname="spec.features.failure_spec_1" name="baz" file="./spec/features/failure_spec_1.rb" time="32.297284">
<failure message="example" type="spec.features.failure_spec_1">expected baz</failure>
</testcase>

<testcase classname="spec.features.failure_spec_2" name="baz" file="./spec/features/failure_spec_2.rb" time="1.470356">
<failure message="RSpec::Core::MultipleExceptionError" type="RSpec::Core::MultipleExceptionError">
</testcase>

<testcase classname="spec.features.failure_spec_3" name="baz" file="./spec/features/failure_spec_3.rb" time="1.470356">
<failure>Something wrong!</failure>
</testcase>
</testsuite>
